### ISSUE TITLE
Create a plan of works on Ms thesis

### ISSUE THREAD

**Issue by iradche** [IPMITMO/odva#6]
- [x]  Define a goal and the tasks (https://github.com/IPMITMO/odva/issues/8).
- [ ]  Choose development tools (https://github.com/IPMITMO/odva/issues/9).
- [ ]  Write "user story" of data validity rules and regulations (https://github.com/IPMITMO/odva/issues/10). 
- [ ]  Write chapter 1 of thesis (https://github.com/IPMITMO/odva/issues/7).
